configs:
- id: env
  config:
    name: env
    template: env.json
    skip: false
  type:
    api: auto-tag
- id: app
  config:
    name: app
    template: app.json
    skip: false
  type:
    api: auto-tag
