configs:
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    template: application-web.json
    skip: false
  type:
    api: application-web
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    parameters:
      applicationId:
        configId: config-xx
        configType: application-web
        property: id
        type: reference
      pattern:
        name: Appname
        type: environment
    template: application-detection-rule.json
    skip: false
  type:
    api: app-detection-rule
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    parameters:
      mzid:
        configId: config-xx
        configType: builtin:management-zones
        property: id
        type: reference
    template: alerting-profile.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.profile
      scope: environment
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    template: management-zone.json
    skip: false
  type:
    settings:
      schema: builtin:management-zones
      scope: environment
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    parameters:
      alertingprofileId:
        configId: config-xx
        configType: builtin:alerting.profile
        property: id
        type: reference
      email:
        name: Email
        type: environment
    template: notification.json
    skip: false
  type:
    api: notification
- id: config-xx
  config:
    name:
      name: Appname    
      type: environment
    parameters:
      mzid:
        configId: config-xx
        configType: builtin:management-zones
        property: id
        type: reference
    template: maintenance-window.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      scope: environment
- id: config-xx
  config:
    name:
      name: Appname
      type: environment
    parameters:
      appname:
        name: Appname
        type: environment
      domain:
        name: Hostname
        type: environment
      mzid:
        configId: config-xx
        configType: builtin:management-zones
        property: id
        type: reference
      owner:
        name: Email
        type: environment
    template: dashboard.json
    skip: false
  type:
    api: dashboard
- id: tag-env
  config:
    name: env
    template: auto-tag-env.json
    skip: false
  type:
    api: auto-tag
- id: tag-app
  config:
    name: app
    template: auto-tag-app.json
    skip: false
  type:
    api: auto-tag
- id: host-naming
  config:
    name: host-naming
    template: conditional-naming-host.json
    skip: false
  type:
    api: conditional-naming-host
- id: processgroup-naming
  config:
    name: processgroup-naming
    template: conditional-naming-processgroup.json
    skip: false
  type:
    api: conditional-naming-processgroup
- id: service-naming-nginx
  config:
    name: service-naming-nginx
    template: conditional-naming-service-nginx.json
    skip: false
  type:
    api: conditional-naming-service
- id: service-naming
  config:
    name: service-naming
    template: conditional-naming-service.json
    skip: false
  type:
    api: conditional-naming-service

    
