configs:
- id: service-naming-1
  config:
    name: service-naming-nginx
    template: service-naming-nginx.json
    skip: false
  type:
    api: conditional-naming-service
- id: service-naming-2
  config:
    name: service-naming
    template: service-naming.json
    skip: false
  type:
    api: conditional-naming-service
