configs:
- id: mw-1
  config:
    name:
      name: Appname
      type: environment
    parameters:
      mzid:
        configId: Appname
        configType: management-zone
        property: id
        type: reference
    template: training.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.maintenance-window
      scope: environment:
